/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import javax.swing.JOptionPane;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JFrame;

/**
 *
 * @author Ahmad Nur Latif P
 */
public class menu_test extends javax.swing.JFrame {

    /**
     * Creates new form menu_utama
     */
    public menu_test() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setupResizeListener();
        String kasir = UserID.getNamaKasir();
        label_selamatdatang.setText("Hallo, "+kasir);
        tampilkanTanggal_hariini();
        tampilalamatService();
        tampilkanWaktuSekarang();
        waktuBerjalan();
    }
    
    private void setupResizeListener() {
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                refreshLayeredPane();
            }
        });
    }
    
    private void refreshLayeredPane() {
        if (jLayeredPane1.getComponentCount() > 0) {
            java.awt.Component comp = jLayeredPane1.getComponent(0);

            comp.setBounds(0, 0, jLayeredPane1.getWidth(), jLayeredPane1.getHeight());

            jLayeredPane1.revalidate();
            jLayeredPane1.repaint();
        }
    }
    
    // Method untuk load panel ke layeredPane
    private void loadPanel(javax.swing.JPanel panel) {
    jLayeredPane1.removeAll();
    javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(panel);
    scrollPane.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
    scrollPane.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
    jLayeredPane1.add(scrollPane, java.awt.BorderLayout.CENTER);
    
    jLayeredPane1.revalidate();
    jLayeredPane1.repaint();
}
    

    private void tampilkanTanggal_hariini() {
        Date tanggalSaatIni = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("EEEE,dd-MM-yyyy");
        String tanggalFormatted = formatter.format(tanggalSaatIni);
        tanggal_label.setText(tanggalFormatted);
    }

    private void tampilkanWaktuSekarang() {
        Date waktuSaatIni = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("HH:mm:ss");
        String waktuFormatted = formatter.format(waktuSaatIni);
        jam_label.setText(waktuFormatted);
    }

    private void waktuBerjalan() {
        int delay = 1000;
        Timer waktu = new Timer(delay, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tampilkanWaktuSekarang();
            }
        });
        waktu.start();
    }

    private void tampilalamatService() {
        String teksAlamatPanjang = "ITC DEPOK, LANTAI 3 NOMOR 129, Telp 0821-1460-1461";
        alamat_label.setText("<html><p style=' text-align: center;'>" + teksAlamatPanjang + "</p></html>");
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_kiri = new javax.swing.JPanel();
        label_selamatdatang = new javax.swing.JLabel();
        tanggal_label = new javax.swing.JLabel();
        jam_label = new javax.swing.JLabel();
        alamat_label = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rep_teknisi = new javax.swing.JMenuBar();
        master = new javax.swing.JMenu();
        menu_teknisi = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menu_pelanggan = new javax.swing.JMenuItem();
        menu_sparepart = new javax.swing.JMenuItem();
        menu_aksesoris = new javax.swing.JMenuItem();
        menu_service = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        menu_pembayaran = new javax.swing.JMenuItem();
        report = new javax.swing.JMenu();
        menu_rtkasir = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menu_rpelanggan = new javax.swing.JMenuItem();
        menu_rsparepart = new javax.swing.JMenuItem();
        menu_raksesoris = new javax.swing.JMenuItem();
        menu_rservice = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        riwayat_transaksi = new javax.swing.JMenuItem();
        keluar = new javax.swing.JMenu();
        menu_keluarakun = new javax.swing.JMenuItem();
        menu_keluarapk = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panel_kiri.setBackground(new java.awt.Color(102, 102, 255));
        panel_kiri.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 3, new java.awt.Color(0, 0, 0)));

        label_selamatdatang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_selamatdatang.setForeground(new java.awt.Color(255, 255, 255));
        label_selamatdatang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_selamatdatang.setText("HALLO");
        label_selamatdatang.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        tanggal_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tanggal_label.setForeground(new java.awt.Color(255, 255, 255));
        tanggal_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tanggal_label.setText("Tanggal Hari Ini");

        jam_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jam_label.setForeground(new java.awt.Color(255, 255, 255));
        jam_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jam_label.setText("Jam Hari Ini");

        alamat_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        alamat_label.setForeground(new java.awt.Color(255, 255, 255));
        alamat_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alamat_label.setText("TEKS ALAMAT SUPER CELULER");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/super_170_196.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_kiriLayout = new javax.swing.GroupLayout(panel_kiri);
        panel_kiri.setLayout(panel_kiriLayout);
        panel_kiriLayout.setHorizontalGroup(
            panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kiriLayout.createSequentialGroup()
                .addGroup(panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggal_label, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jam_label, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_kiriLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(label_selamatdatang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alamat_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panel_kiriLayout.setVerticalGroup(
            panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kiriLayout.createSequentialGroup()
                .addComponent(tanggal_label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jam_label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_selamatdatang, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alamat_label, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLayeredPane1.setBackground(new java.awt.Color(102, 102, 255));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLayeredPane1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/menu_super.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );

        jLayeredPane1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(panel_kiri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_kiri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        rep_teknisi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rep_teknisi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rep_teknisi.setName(""); // NOI18N
        rep_teknisi.setPreferredSize(new java.awt.Dimension(344, 35));

        master.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/teknisi.png"))); // NOI18N
        master.setText("Master |");
        master.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        master.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        master.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        menu_teknisi.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_teknisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kasir.png"))); // NOI18N
        menu_teknisi.setText("Kasir");
        menu_teknisi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_teknisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_teknisiActionPerformed(evt);
            }
        });
        master.add(menu_teknisi);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/teknisi.png"))); // NOI18N
        jMenuItem2.setText("Teknisi");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        master.add(jMenuItem2);

        menu_pelanggan.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_pelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pelanggan.png"))); // NOI18N
        menu_pelanggan.setText("Pelanggan");
        menu_pelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pelangganActionPerformed(evt);
            }
        });
        master.add(menu_pelanggan);

        menu_sparepart.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_sparepart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/sparepart.png"))); // NOI18N
        menu_sparepart.setText("Sparepart");
        menu_sparepart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_sparepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_sparepartActionPerformed(evt);
            }
        });
        master.add(menu_sparepart);

        menu_aksesoris.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_aksesoris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/aksesoris.png"))); // NOI18N
        menu_aksesoris.setText("Aksesoris");
        menu_aksesoris.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_aksesoris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_aksesorisActionPerformed(evt);
            }
        });
        master.add(menu_aksesoris);

        menu_service.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_service.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/service.png"))); // NOI18N
        menu_service.setText("Service");
        menu_service.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_serviceActionPerformed(evt);
            }
        });
        master.add(menu_service);

        rep_teknisi.add(master);

        transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/transaction.png"))); // NOI18N
        transaksi.setText("Transaksi |");
        transaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transaksi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menu_pembayaran.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_pembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/transaction.png"))); // NOI18N
        menu_pembayaran.setText("Nota Service");
        menu_pembayaran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pembayaranActionPerformed(evt);
            }
        });
        transaksi.add(menu_pembayaran);

        rep_teknisi.add(transaksi);

        report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/printer.png"))); // NOI18N
        report.setText("Report |");
        report.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        report.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menu_rtkasir.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_rtkasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/printer.png"))); // NOI18N
        menu_rtkasir.setText("Data Kasir");
        menu_rtkasir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_rtkasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_rtkasirActionPerformed(evt);
            }
        });
        report.add(menu_rtkasir);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/printer.png"))); // NOI18N
        jMenuItem3.setText("Data Teknisi");
        report.add(jMenuItem3);

        menu_rpelanggan.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_rpelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/printer.png"))); // NOI18N
        menu_rpelanggan.setText("Data Pelanggan");
        menu_rpelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_rpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_rpelangganActionPerformed(evt);
            }
        });
        report.add(menu_rpelanggan);

        menu_rsparepart.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_rsparepart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/printer.png"))); // NOI18N
        menu_rsparepart.setText("Data Sparepart");
        menu_rsparepart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_rsparepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_rsparepartActionPerformed(evt);
            }
        });
        report.add(menu_rsparepart);

        menu_raksesoris.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_raksesoris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/printer.png"))); // NOI18N
        menu_raksesoris.setText("Data Aksesoris");
        menu_raksesoris.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_raksesoris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_raksesorisActionPerformed(evt);
            }
        });
        report.add(menu_raksesoris);

        menu_rservice.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_rservice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/printer.png"))); // NOI18N
        menu_rservice.setText("Data Service");
        menu_rservice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_rservice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_rserviceActionPerformed(evt);
            }
        });
        report.add(menu_rservice);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/printer.png"))); // NOI18N
        jMenuItem1.setText("Data Penjualan");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        report.add(jMenuItem1);

        riwayat_transaksi.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        riwayat_transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/printer.png"))); // NOI18N
        riwayat_transaksi.setText("Data Riwayat Transaksi");
        riwayat_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riwayat_transaksiActionPerformed(evt);
            }
        });
        report.add(riwayat_transaksi);

        rep_teknisi.add(report);

        keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/exit.png"))); // NOI18N
        keluar.setText("Keluar |");
        keluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        menu_keluarakun.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_keluarakun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/login.png"))); // NOI18N
        menu_keluarakun.setText("Keluar Akun");
        menu_keluarakun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_keluarakun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_keluarakunActionPerformed(evt);
            }
        });
        keluar.add(menu_keluarakun);

        menu_keluarapk.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_keluarapk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/exit.png"))); // NOI18N
        menu_keluarapk.setText("Keluar Aplikasi");
        menu_keluarapk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_keluarapk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_keluarapkActionPerformed(evt);
            }
        });
        keluar.add(menu_keluarapk);

        rep_teknisi.add(keluar);

        setJMenuBar(rep_teknisi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed

    }//GEN-LAST:event_keluarActionPerformed

    private void menu_keluarakunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_keluarakunActionPerformed
        this.dispose();
        login keluarakun = new login();
        keluarakun.setVisible(true);
        keluarakun.setLocationRelativeTo(null);    // TODO add your handling code here:
    }//GEN-LAST:event_menu_keluarakunActionPerformed

    private void menu_rtkasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_rtkasirActionPerformed
        loadPanel(new form_report.report_kasir().getMainPanel());
    }//GEN-LAST:event_menu_rtkasirActionPerformed

    private void menu_teknisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_teknisiActionPerformed
        loadPanel(new master_kasir().getMainPanel());
    }//GEN-LAST:event_menu_teknisiActionPerformed

    private void menu_keluarapkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_keluarapkActionPerformed
        int konfirmasi_keluarapp = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
        if (konfirmasi_keluarapp == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menu_keluarapkActionPerformed

    private void menu_raksesorisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_raksesorisActionPerformed
        loadPanel(new form_report.report_aksesoris().getMainPanel());
    }//GEN-LAST:event_menu_raksesorisActionPerformed

    private void menu_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pelangganActionPerformed
        loadPanel(new master_pelanggan().getMainPanel());
    }//GEN-LAST:event_menu_pelangganActionPerformed

    private void menu_sparepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_sparepartActionPerformed
        loadPanel(new master_sparepart().getMainPanel());
    }//GEN-LAST:event_menu_sparepartActionPerformed

    private void menu_aksesorisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_aksesorisActionPerformed
        loadPanel(new master_aksesoris().getMainPanel());
    }//GEN-LAST:event_menu_aksesorisActionPerformed

    private void menu_serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_serviceActionPerformed
        loadPanel(new master_service().getMainPanel());
    }//GEN-LAST:event_menu_serviceActionPerformed

    private void menu_rpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_rpelangganActionPerformed
        loadPanel(new form_report.report_pelanggan().getMainPanel());
    }//GEN-LAST:event_menu_rpelangganActionPerformed

    private void menu_rsparepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_rsparepartActionPerformed
        loadPanel(new form_report.report_sparepart().getMainPanel());
    }//GEN-LAST:event_menu_rsparepartActionPerformed

    private void menu_rserviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_rserviceActionPerformed
        loadPanel(new form_report.report_service().getMainPanel());
    }//GEN-LAST:event_menu_rserviceActionPerformed

    private void menu_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pembayaranActionPerformed
        loadPanel(new transaksi_pembayaran().getMainPanel());
    }//GEN-LAST:event_menu_pembayaranActionPerformed

    private void riwayat_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riwayat_transaksiActionPerformed
        loadPanel(new form_report.riwayat_transaksi().getMainPanel());
    }//GEN-LAST:event_riwayat_transaksiActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        loadPanel(new form_report.report_penjualan().getMainPanel());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_test().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jam_label;
    private javax.swing.JMenu keluar;
    private javax.swing.JLabel label_selamatdatang;
    private javax.swing.JMenu master;
    private javax.swing.JMenuItem menu_aksesoris;
    private javax.swing.JMenuItem menu_keluarakun;
    private javax.swing.JMenuItem menu_keluarapk;
    private javax.swing.JMenuItem menu_pelanggan;
    private javax.swing.JMenuItem menu_pembayaran;
    private javax.swing.JMenuItem menu_raksesoris;
    private javax.swing.JMenuItem menu_rpelanggan;
    private javax.swing.JMenuItem menu_rservice;
    private javax.swing.JMenuItem menu_rsparepart;
    private javax.swing.JMenuItem menu_rtkasir;
    private javax.swing.JMenuItem menu_service;
    private javax.swing.JMenuItem menu_sparepart;
    private javax.swing.JMenuItem menu_teknisi;
    private javax.swing.JPanel panel_kiri;
    private javax.swing.JMenuBar rep_teknisi;
    private javax.swing.JMenu report;
    private javax.swing.JMenuItem riwayat_transaksi;
    private javax.swing.JLabel tanggal_label;
    private javax.swing.JMenu transaksi;
    // End of variables declaration//GEN-END:variables
}
