/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form_popup;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import form.transaksi_pembayaran;
import form.transaksi_pembayaran;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
/**
 *
 * @author Ahmad Nur Latif P
 */
public class poppup_sparepart extends javax.swing.JFrame {
private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    public transaksi_pembayaran sppt = null;
    private String filterJenisService;
    /**
     * Creates new form poppup_sparepart
     */
    public poppup_sparepart(transaksi_pembayaran tp, String jenisService) {
        this.sppt = tp;
        this.filterJenisService = jenisService;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        if (filterJenisService != null && !filterJenisService.isEmpty()) {
            this.setTitle("Pilih Sparepart - " + filterJenisService);
            jLabel9.setText("Cari Sparepart untuk jenis: " + filterJenisService);
        }
        datatable();
    }
    
     public poppup_sparepart() {
        this.filterJenisService = null;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setTitle("Pilih Sparepart - Semua Jenis");
        datatable();
    }
    
    protected void datatable() {
    Object[] Baris = {"Kode Barang", "Nama Barang", "Harga Beli (Rp)", "Harga Jual (Rp)", "Jenis Service Barang", "Merk Barang"};
    tabmode = new DefaultTableModel(null, Baris);
    String cariitem = cari_sparepart.getText().trim();

    String sql;
    boolean hasFilter = (filterJenisService != null && !filterJenisService.isEmpty());
    
    try {
        // Build SQL berdasarkan filter
        if (hasFilter) {
            sql = "SELECT * FROM tb_sparepart WHERE jenis_barang = ? AND ("
                + "kd_barang LIKE ? OR "
                + "nama_barang LIKE ? OR "
                + "harga_beli LIKE ? OR "
                + "harga_jual LIKE ? OR "
                + "merk_barang LIKE ?) "
                + "ORDER BY kd_barang ASC";
        } else {
            sql = "SELECT * FROM tb_sparepart WHERE "
                + "kd_barang LIKE ? OR "
                + "nama_barang LIKE ? OR "
                + "harga_beli LIKE ? OR "
                + "harga_jual LIKE ? OR "
                + "jenis_barang LIKE ? OR "
                + "merk_barang LIKE ? "
                + "ORDER BY kd_barang ASC";
        }
        try (PreparedStatement stat = conn.prepareStatement(sql)) {
            int paramIndex = 1;

            if (hasFilter) {
                stat.setString(paramIndex++, filterJenisService);
            }
            int searchParamCount = hasFilter ? 5 : 6;
             for (int i = 0; i < searchParamCount; i++) {
                stat.setString(paramIndex++, "%" + cariitem + "%");
            }
            try (ResultSet hasil = stat.executeQuery()) {
                int rowCount = 0;
                while (hasil.next()) {
                    tabmode.addRow(new Object[]{
                        hasil.getString(1),
                        hasil.getString(2),
                        hasil.getString(3),
                        hasil.getString(4),
                        hasil.getString(5),
                        hasil.getString(6)
                    });
                    rowCount++;
                }

                tblsparepart.setModel(tabmode);
                String labelText = hasFilter 
                    ? " (Jenis Service: " + filterJenisService + ") - " + rowCount + " item ditemukan"
                    : "Cari - " + rowCount + " item ditemukan";
                jLabel9.setText(labelText);
                
                // jika data kosong dengan filter
                if (hasFilter && rowCount == 0) {
                    JOptionPane.showMessageDialog(this, 
                        "Tidak ada sparepart dengan jenis service: ( " + filterJenisService + " )\n" +
                        "Silakan tambahkan data di Master Sparepart.", 
                        "Sparepart Tidak Ditemukan", 
                        JOptionPane.WARNING_MESSAGE);
                }
            }
        }    
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, 
            "Data gagal dipanggil: " + e.getMessage(), 
            "Error Database", 
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsparepart = new javax.swing.JTable();
        cari_sparepart = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tblsparepart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblsparepart.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblsparepart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblsparepart.setGridColor(new java.awt.Color(255, 255, 255));
        tblsparepart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsparepartMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblsparepart);

        cari_sparepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_sparepartActionPerformed(evt);
            }
        });
        cari_sparepart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cari_sparepartKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cari_sparepartKeyReleased(evt);
            }
        });

        bcari.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bcari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/search.png"))); // NOI18N
        bcari.setText("CARI");
        bcari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Keterangan");
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cari_sparepart, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bcari)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(13, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cari_sparepart, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bcari, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblsparepartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsparepartMouseClicked
        int tbpl = tblsparepart.getSelectedRow();
        if (tbpl >= 0 && sppt != null) {
        sppt.kd_bar = tblsparepart.getValueAt(tbpl, 0).toString();
        sppt.nama_bar = tblsparepart.getValueAt(tbpl, 1).toString();
        sppt.harga_bel_bar = tblsparepart.getValueAt(tbpl, 2).toString();
        sppt.harga_ju_bar = tblsparepart.getValueAt(tbpl, 3).toString();
        sppt.merk_bar = tblsparepart.getValueAt(tbpl, 5).toString();
        sppt.itemTerpilihSppt();
        this.dispose();
        } else if (sppt == null) {
        JOptionPane.showMessageDialog(this, 
            "Error: Parent window tidak terdaftar", 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tblsparepartMouseClicked

    private void cari_sparepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_sparepartActionPerformed

    }//GEN-LAST:event_cari_sparepartActionPerformed

    private void cari_sparepartKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cari_sparepartKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            datatable();
        }
    }//GEN-LAST:event_cari_sparepartKeyPressed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        datatable();
    }//GEN-LAST:event_bcariActionPerformed

    private void cari_sparepartKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cari_sparepartKeyReleased
        datatable();
    }//GEN-LAST:event_cari_sparepartKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(poppup_sparepart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(poppup_sparepart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(poppup_sparepart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(poppup_sparepart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new poppup_sparepart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcari;
    private javax.swing.JTextField cari_sparepart;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblsparepart;
    // End of variables declaration//GEN-END:variables
}
